name: release
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Deploy
        run: |
          docker build -t 'back_web' .
          docker run -d -p 6002:8080 --name=web_app --mount source=weblog,target=/app/log --mount type=bind,source=/www/wwwroot/pull.wghtstudio.cn/avatar/web,target=/app/avatar --mount type=bind,source=/www/wwwroot/pull.wghtstudio.cn/img,target=/app/img back_web
